name: WarpPlugin
version: 1.0.1
main: com.rafaelpiloto10.warpplugin.Main
description: Plugin that allows custom warps
author: Rafael Piloto
website: https://github.com/RafaelPiloto10/WarpPlugin/

commands:
  warp:
    description: warp to location